version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  build-tests:
    jobs:
      - run_tests:
          context: store
jobs:
  run_tests:
    docker: #where things will be ran(docker, windows, mac, virtual machine)
      - image: circleci/node
      - image: circleci/mongo:4.0.28
        environment:
          MONGO_USERNAME: mongouser
          MONGO_PASSWORD: mongopass
    steps:
      - run:
          name: MongoDB Install
          command: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - node/install:
          node-version: "14.18.0" #not sure why its failing
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get versions
          command: |
            node -v
            npm -v
            mongo --version
            mongo localhost --eval "db.version()"
      - run:
          name: Run Database/Server Unit Tests
          command: |
            node ./node_modules/mocha/bin/mocha **/*-test.js --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results --exit
